module.exports = {
  // MISC
  FIREBASE: 'https://worlddominationsummit.firebaseio.com',

  SET_AUTH_ME: 'SET_AUTH_ME',
  CONFIRM_AUTH: 'SET_AUTH_CONFIRMED',
  ATTEMPT_LOGIN: 'ATTEMPT_LOGIN',
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  SET_CARD: 'SET_CARD',
  SET_USE_EXISTING_CARD: 'SET_USE_EXISTING_CARD',
  SET_RESET_STATUS: 'SET_RESET_STATUS',
  SET_RESET_ERROR: 'SET_RESET_ERROR',

  // MAIN PANEL ACTIONS
  SET_MODAL_OPEN: 'SET_MODAL_OPEN',
  SET_MODAL_CLOSED: 'SET_MODAL_CLOSED',
  SET_MODAL_VISIBILITY: 'SET_MODAL_VISIBILITY',

  // CHECKOUT
  SET_CHECKOUT_STATUS: 'SET_CHECKOUT_STATUS',
  SET_CHECKOUT_QUANTITY: 'SET_CHECKOUT_QUANTITY',
  SET_CHECKOUT_ERROR: 'SET_CHECKOUT_ERROR',

};
